FROM node:19.6.0-alpine3.16 AS build

WORKDIR /kamala_facts

COPY package* yarn.lock ./

RUN yarn install --immutable --immutable-cache --check-cache

COPY public ./public

COPY src ./src

COPY . .

RUN yarn build


FROM nginx:1.23.3 AS prod

COPY --from=build /kamala_facts/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

