FROM node:16-alpine3.11 AS build

WORKDIR /kamala_facts

COPY package* package-lock.json ./

RUN npm ci --production

COPY public ./public

COPY src ./src

COPY . .

RUN npm run build


FROM nginx:1.21.3 AS prod

COPY --from=build /kamala_facts/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

